pool:
   vmImage: 'macOS 10.13'
variables:
  DESTINATION: 'platform=iOS Simulator,name=iPhone 7,OS=latest'

steps:
- script: |
    sudo xcode-select /Applications/Xcode_10.0.0.app
    carthage bootstrap --platform ios
  env: 
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
  displayName: "Setup environment"
- script: |
    xcodebuild -scheme 'Wire-iOS' -destination "$(DESTINATION)" -derivedDataPath DerivedData -enableCodeCoverage YES build-for-testing
  displayName: "Build"
- script: |
    xcodebuild -scheme 'Wire-iOS' -destination "$(DESTINATION)" -derivedDataPath DerivedData -enableCodeCoverage YES test-without-building
  displayName: "Test"
