pool:
   vmImage: 'macOS 10.13'
variables:
  DESTINATION: 'platform=iOS Simulator,name=iPhone 7,OS=latest'

steps:
- script: |
    ./setup.sh
  env: 
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
  displayName: "Setup environment"
- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    xcodeVersion: 10
    args: "-scheme Wire-iOS -destination $(DESTINATION) -derivedDataPath DerivedData -enableCodeCoverage YES -quiet"
  displayName: "Build"
- task: Xcode@5
  inputs:
    actions: 'test-without-building'
    xcodeVersion: 10
    useXcpretty: true
    publishJUnitResults: true
    args: "-scheme Wire-iOS -destination $(DESTINATION) -derivedDataPath DerivedData -enableCodeCoverage YES"
  displayName: "Test"
